### ISSUE TITLE
Outstanding Tasks

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#208]
Hi @Rob1Paul 

I hope you’re well.

The four of us had a meeting this morning to review all of the outstanding issues we discussed on Friday & in your GitHub issue. There are quite a few issues which fall out of the MVP scope (see below for a full list). We estimate, based on feedback from Dan, that it will require a week’s worth of work from each of us (so 20 days work in total) to complete all outstanding issues.

Let me know your thoughts. We are all keen to get started on this ASAP if you’re happy.

__

## Outstanding tasks outside of the MVP scope

* More padding on the right of get started
* Check ‘hand’ appears when you hover   over all ‘get started’ buttons and all buttons in sign up form
* Home splash still not perfect on some   devices. Needs more space between text and images. We will explore separate   images and slightly fading images into the background
* Green arrows between join, connect and   read.
* Step 3 – update copy – see doc. ‘Sign   Up
* Remove full stops on headings
* Make the text on the 3 steps clearer/   larger (Contact Details etc..)
* Maintain the user's form data when   going back
* First Step – Remove text ‘Let's get the   ball rolling...’
* Remove 'We'll use this to introduce you  to your reading partner'
* Remove (How rude)
* Slightly more spacing between   Reader/listener question and book preference question – and shift both down a   touch from time zone question
* ‘Would you rather be a Reader or a   Listener?’ – Needs a question mark
* Answers should be Reader and listener –   add ‘er’: 3 options should be i Reader, ii Listener iii Don’t mind (try   both)
* Make ‘Need Tips’ more beautiful
* Remove Go back to homepage from the   thank you page
* Remove the words ‘That’s the hard part   done. Welcome to our community’. from the thank you page.
* Make social buttons our colour scheme,   or at least email one
* Below ‘Help Spread The Word’ heading   change text to ‘Why not share the story of Audrey?’
* Instead of ‘Have a great day!’ put   ‘Happy reading!’
Answers justified
* Question and answers laid out similar   to https://www.sofarsounds.com/faq i.e. click to open answer
* Heading for each section to be on left,   not centred
* All headings to be the same size, so   ‘definitions and interpretations’ needs to be smaller
* Last line on privacy page ‘You may   contact….’ To be the same size as other text
* Heads to be same size as on privacy   page (i.e. same size as heading ‘Scope of this privacy policy’). So headings   should be smaller
* All text should be the same size, so   make text in introduction smaller, like other text
* Change over email address – what email   address (readwithaudrey@gmail.com or robsupport@readwithaudrey.com). TBC
* Adding a transactional email ‘don’t  forget to book your reading session with your partner’ (say 36 hrs after pairing.)
* Make sure auto
* Update transactional email headers as   per dropbox file
* Check whether pair introduction   transactional email will send if no attachments in the appropriate airtable   field/cell. Would like this to be possible as I start to test other reading   options as alternative to pdfs
* Sendgrid unsubscribe set
* Looking for pair should be false when   pairs are matched
* pairing status default as active
* Migration to readwithaudrey domain.

**Comment by Rob1Paul** [comment]
Hi @matthall8 Thanks for your message. I hadn't anticipated how much time would be required to complete the various outstanding tasks, and quite how many would fall outside the scope.   

As a next step, I have placed in bold below those tasks I consider a priority which fall outside the scope. 
Perhaps you could let me know the total number of work days required to complete these tasks only. 
Thanks.


Outstanding tasks outside of the MVP scope


* ** More padding on the right of get started**
* Check ‘hand’ appears when you hover   over all ‘get started’ buttons and all buttons in sign up form
* **Home splash still not perfect on some   devices. Needs more space between text and images. We will explore separate   images and slightly fading images into the background**
* Green arrows between join, connect and   read.
* Step 3 – update copy – see doc. ‘Sign   Up
* Remove full stops on headings
* Make the text on the 3 steps clearer/   larger (Contact Details etc..)
* Maintain the user's form data when   going back
* First Step – Remove text ‘Let's get the   ball rolling...’
* Remove 'We'll use this to introduce you  to your reading partner'
* Remove (How rude)
* Slightly more spacing between   Reader/listener question and book preference question – and shift both down a   touch from time zone question
* ** ‘Would you rather be a Reader or a   Listener?’ – Needs a question mark**
* **Answers should be Reader and listener –   add ‘er’: 3 options should be i Reader, ii Listener iii Don’t mind (try both)**
* Make ‘Need Tips’ more beautiful
* Remove Go back to homepage from the   thank you page
* Remove the words ‘That’s the hard part   done. Welcome to our community’. from the thank you page.
* Make social buttons our colour scheme,   or at least email one
* Below ‘Help Spread The Word’ heading   change text to ‘Why not share the story of Audrey?’
* Instead of ‘Have a great day!’ put   ‘Happy reading!’
Answers justified
* Question and answers laid out similar   to https://www.sofarsounds.com/faq i.e. click to open answer
* Heading for each section to be on left,   not centred
* All headings to be the same size, so   ‘definitions and interpretations’ needs to be smaller
* Last line on privacy page ‘You may   contact….’ To be the same size as other text
* Heads to be same size as on privacy   page (i.e. same size as heading ‘Scope of this privacy policy’). So headings   should be smaller
* All text should be the same size, so   make text in introduction smaller, like other text
* **Change over email address – what email   address (readwithaudrey@gmail.com or robsupport@readwithaudrey.com). TBC**
* Adding a transactional email ‘don’t  forget to book your reading session with your partner’ (say 36 hrs after pairing.)
* Make sure auto????? assume you meant this one...
**Make sure auto-generated transactional sendgrid emails appears in email outbox as verification email has been sent (important).**

* Update transactional email headers as   per dropbox file
* **Check whether pair introduction   transactional email will send if no attachments in the appropriate airtable   field/cell. Would like this to be possible as I start to test other reading   options as alternative to pdfs**
* Sendgrid unsubscribe set
* Looking for pair should be false when   pairs are matched
* pairing status default as active
* **Migration to readwithaudrey domain.**

**Comment by matthall8** [comment]
Morning @Rob1Paul,

We estimate that it would take 10 days of work to complete the tasks you have bolded.

Let me know your thoughts.

**Comment by Rob1Paul** [comment]
@matthall8 @DenisKent similar problem encountered with other pages e.g. homepage. and I'm unable to view any of the three form pages. Thanks

**Comment by matthall8** [comment]
Hey @Rob1Paul - this has been noted and fixed already locally (https://github.com/ReadWithAudrey/readwithaudrey/issues/229). We should deploy the fix to master this morning.

**Comment by Rob1Paul** [comment]
@matthall8 Thanks for letting me know.

**Comment by matthall8** [comment]
This should now be fixed @Rob1Paul - can you let me or @BenNewman90 know if it's not.

**Comment by Rob1Paul** [comment]
Hi @matthall8 @BenNewman90 @DenisKent @sbinlondon  

I am still getting various error messages when trying to update content....

![image](https://user-images.githubusercontent.com/43749507/47847882-81742080-ddc4-11e8-8a7f-7ed29b24cfaf.png)


![image](https://user-images.githubusercontent.com/43749507/47847905-96e94a80-ddc4-11e8-8893-9a171225dcac.png)



![image](https://user-images.githubusercontent.com/43749507/47848012-e16ac700-ddc4-11e8-8c76-d6888559c261.png)

**Comment by BenNewman90** [comment]
@Rob1Paul this has been addressed and awaiting a merge.
